services:
  - type: web
    name: stock-position-manager-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_VERSION
        value: 20
      - key: ANGEL_API_KEY
        sync: false
      - key: ANGEL_CLIENT_CODE
        sync: false
      - key: ANGEL_PASSWORD
        sync: false
      - key: ANGEL_TOTP_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
